# Generated by Django 5.2.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Data prevista do evento')),
                ('guests_estimate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº estimado de convidados')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local previsto')),
                ('budget_range', models.CharField(choices=[('ate_500k', 'Até 500.000 Kz'), ('500k_2m', '500.000 - 2.000.000 Kz'), ('2m_5m', '2.000.000 - 5.000.000 Kz'), ('acima_5m', 'Acima de 5.000.000 Kz'), ('a_definir', 'A definir')], default='a_definir', max_length=20, verbose_name='Faixa de orçamento')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem adicional')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em Análise'), ('respondido', 'Respondido'), ('convertido', 'Convertido em Cliente'), ('recusado', 'Recusado')], default='novo', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('services', models.ManyToManyField(blank=True, to='services.service', verbose_name='Serviços desejados')),
            ],
            options={
                'verbose_name': 'Pedido de Orçamento',
                'verbose_name_plural': 'Pedidos de Orçamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
