# Generated by Django 5.2.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=200, verbose_name='Descrição curta')),
                ('description', models.TextField(verbose_name='Descrição completa')),
                ('icon', models.CharField(help_text='Ex: speaker, lightbulb, camera', max_length=60, verbose_name='Ícone (nome lucide-react)')),
                ('cover_image', models.ImageField(upload_to='services/', verbose_name='Imagem de capa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'title'],
            },
        ),
    ]
