# Generated by Django 5.2.7 on 2026-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descrição completa'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='Descrição completa'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_pt',
            field=models.CharField(max_length=120, null=True, verbose_name='Título'),
        ),
    ]
