# Generated by Django 5.2.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('about_text', models.TextField(verbose_name='Texto "Sobre Nós"')),
                ('mission', models.TextField(blank=True, verbose_name='Missão')),
                ('vision', models.TextField(blank=True, verbose_name='Visão')),
                ('values', models.TextField(blank=True, verbose_name='Valores')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Anos de experiência')),
                ('events_completed', models.PositiveIntegerField(default=0, verbose_name='Eventos realizados')),
                ('artists_count', models.PositiveIntegerField(default=0, verbose_name='Artistas na agência')),
                ('happy_clients', models.PositiveIntegerField(default=0, verbose_name='Clientes satisfeitos')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Endereço')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
