# Generated by Django 5.2.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('event_type', models.CharField(choices=[('corporativo', 'Evento Corporativo'), ('show', 'Show/Concerto'), ('festival', 'Festival'), ('privado', 'Evento Privado'), ('casamento', 'Casamento'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de evento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_start', models.DateTimeField(verbose_name='Data/hora de início')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de fim')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cover_image', models.ImageField(upload_to='events/covers/', verbose_name='Imagem de capa')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='artists.artist', verbose_name='Artistas')),
                ('services_used', models.ManyToManyField(blank=True, related_name='events', to='services.service', verbose_name='Serviços utilizados')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date_start'],
            },
        ),
    ]
