# Generated by Django 5.2.7 on 2026-07-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('media_type', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Imagem')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do vídeo (YouTube/Vimeo)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='events.event', verbose_name='Evento relacionado')),
            ],
            options={
                'verbose_name': 'Item da Galeria',
                'verbose_name_plural': 'Galeria',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
