# Generated by Django 5.2.7 on 2026-07-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('cover_image', models.ImageField(upload_to='news/', verbose_name='Imagem de capa')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_at'],
            },
        ),
    ]
