# Generated by Django 5.2.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('dj', 'DJ'), ('banda', 'Banda'), ('cantor', 'Cantor/Cantora'), ('danca', 'Grupo de Dança'), ('humorista', 'Humorista'), ('outro', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('photo', models.ImageField(upload_to='artists/photos/', verbose_name='Foto de perfil')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artists/covers/', verbose_name='Imagem de capa')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível para contratação')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
