# Generated by Django 5.2.7 on 2026-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio_pt',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
    ]
